# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      Write-Host "Pipeline Variable: $(SAG_HOME)"
      Write-Host "Environment Variable: $Env:SAG_HOME"
      Write-Host "Pipeline Variable: $(SAG_CI_HOME)"
      Write-Host "Environment Variable: $Env:SAG_CI_HOME"
      Write-Host "Pipeline Variable: $(JOB_NAME)"
      Write-Host "Environment Variable: $Env:JOB_NAME"


- task: BatchScript@1
  inputs:
    filename: '$(SAG_HOME)/common/lib/ant/bin/ant'
    arguments: '-DSAGHome=$(SAG_HOME) -DSAG_CI_HOME=$(SAG_CI_HOME) -DprojectName=$(JOB_NAME) build'
 




